# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Automatically triggered on PR
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pr-trigger
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven local repo

  - task: SonarCloudPrepare@3
    displayName: 'Prepare SonarCloud analysis configuration'
    inputs:
      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
      organization: '$(SONARCLOUD_ORG)'
      scannerMode: Other
      extraProperties: |
        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
        sonar.coverage.exclusions=**/config/*,**/*Mock*,**/model/**,**/entity/*
        sonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
        sonar.junit.reportPaths=target/surefire-reports/
        sonar.verbose=true
  - bash: |
      docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite &
    displayName: Run azurite to test Service - Storage integration

  - task: Maven@4
    displayName: 'Validate project (build ecommerce commons project)'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean validate'
      sonarQubeRunAnalysis: false

  - task: Maven@4
    displayName: 'Run Junit Tests'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean verify'
      sonarQubeRunAnalysis: true

  - task: SonarCloudPublish@3
    displayName: 'Publish SonarCloud results on build summary'
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishCodeCoverageResults@2
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'target/site/jacoco/jacoco.xml'
      reportDirectory: 'target/site/jacoco'
    displayName: 'Publish Code Coverage on Azure Devops'
