microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: "pagopaecommercetxschedulerservice-microservice-chart"
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 10
    image:
      repository: pagopaucommonacr.azurecr.io/pagopaecommercetransactionsschedulerservice
      tag: "latest"
    envConfig:
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-transactions-scheduler-service-blue,deployment.environment=uat"
      ECS_SERVICE_NAME: pagopa-ecommerce-transactions-scheduler-service-blue
    envSecret: {}
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaecommercetransactionsschedulerservice
    tag: "3.4.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.ecommerce.internal.uat.platform.pagopa.it"
    path: /pagopa-ecommerce-transactions-scheduler-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 30 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 60
  envConfig:
    MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    ECOMMERCE_DATABASE_NAME: "ecommerce"
    TRANSACTION_EXPIRED_EVENTS_QUEUE_NAME: "pagopa-u-weu-ecommerce-transactions-expiration-queue"
    PENDING_TRANSACTIONS_SCHEDULE_CRON: "0 0 */1 * * *"
    PENDING_TRANSACTIONS_WINDOWS_BATCH_EXECUTION_RATE_MULTIPLIER: "2"
    PENDING_TRANSACTIONS_PARALLEL_EVENTS_TO_PROCESS: "1"
    PENDING_TRANSACTIONS_MAX_TRANSACTIONS_PER_PAGE: "5"
    PENDING_TRANSACTIONS_PAGE_ANALYSIS_DELAY_SECONDS: "1"
    PENDING_TRANSACTIONS_SEND_PAYMENT_RESULT_TIMEOUT_SECONDS: "3900"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-transactions-scheduler-service,deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECS_SERVICE_NAME: pagopa-ecommerce-transactions-scheduler-service
    ECS_SERVICE_ENVIRONMENT: "uat"
    DEAD_LETTER_LISTENER_TRANSACTION_FIXED_DELAY_MILLIS: "1000"
    DEAD_LETTER_LISTENER_TRANSACTION_MAX_MESSAGE_PER_POLL: "1"
    DEAD_LETTER_LISTENER_TRANSACTION_QUEUE_NAME: "pagopa-u-weu-ecommerce-transactions-dead-letter-queue"
    DEAD_LETTER_LISTENER_NOTIFICATION_FIXED_DELAY_MILLIS: "1000"
    DEAD_LETTER_LISTENER_NOTIFICATION_MAX_MESSAGE_PER_POLL: "1"
    DEAD_LETTER_LISTENER_NOTIFICATION_QUEUE_NAME: "pagopa-u-weu-ecommerce-notifications-service-errors-queue"
    ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_ACCOUNT_NAME: pagopauweuecommercedlsa
    ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_ENDPOINT: https://pagopauweuecommercedlsa.queue.core.windows.net/pagopauweuecommercedlsa
    NPG_URI: https://stg-ta.nexigroup.com/api/phoenix-0.0
    NPG_READ_TIMEOUT: "10000"
    NPG_CONNECTION_TIMEOUT: "10000"
    NPG_CARDS_PSP_LIST: "BCITITMM,CIPBITMM,BIC36019,UNCRITMM,BPPIITRRXXX,PPAYITR1XXX,BNLIITRR,PASCITMM,WOLLNLB1,IFSPIT21,BPMOIT22,SARDIT31"
    NPG_PAYPAL_PSP_LIST: "BCITITMM,SIGPITM1XXX,MOONITMMXXX"
    NPG_MYBANK_PSP_LIST: "BCITITMM,UNCRITMM"
    NPG_BANCOMATPAY_PSP_LIST: "BCITITMM"
    NPG_SATISPAY_PSP_LIST: "SATYLUL1"
    NPG_APPLEPAY_PSP_LIST: "SIGPITM1XXX,CIPBITMM,MOONITMMXXX"
    NPG_GOOGLE_PAY_PSP_LIST: "CIPBITMM"
    DEPLOYMENT_VERSION: "PROD"
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    REDIS_STREAM_EVENT_CONTROLLER_STREAM_KEY: "scheduler-service-commands"
    REDIS_STREAM_EVENT_CONTROLLER_CONSUMER_NAME_PREFIX: "scheduler"
    EVENT_CONTROLLER_STATUS_POLLING_CHRON: "*/10 * * * * *"
    TRANSACTIONSVIEW_UPDATE_ENABLED: "true"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    QUEUE_TRANSIENT_CONNECTION_STRING: ecommerce-storage-transient-connection-string
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_KEY: ecommerce-storage-dead-letter-account-key
    NPG_API_KEY: npg-api-key
    NPG_CARDS_PSP_KEYS: npg-cards-psp-keys
    NPG_PAYPAL_PSP_KEYS: npg-paypal-psp-keys
    NPG_BANCOMATPAY_PSP_KEYS: npg-bancomatpay-psp-keys
    NPG_MYBANK_PSP_KEYS: npg-mybank-psp-keys
    NPG_SATISPAY_PSP_KEYS: npg-satispay-psp-keys
    NPG_APPLEPAY_PSP_KEYS: npg-apple-pay-psp-keys
    NPG_GOOGLE_PAY_PSP_KEYS: npg-google-pay-psp-keys
    REDIS_PASSWORD: redis-ecommerce-access-key
    REDIS_HOST: redis-ecommerce-hostname
  keyvault:
    name: "pagopa-u-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  azure:
    workloadIdentityClientId: 449c5b65-f368-487a-881a-b03676420c53
