microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: "pagopaecommercetxschedulerservice-microservice-chart"
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopaucommonacr.azurecr.io/pagopaecommercetransactionsschedulerservice
        tag: "latest"
        pullPolicy: Always
    envConfig:
      MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
      MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
      MONGO_PORT: "10255"
      MONGO_SSL_ENABLED: "true"
      MONGO_MIN_POOL_SIZE: "0"
      MONGO_MAX_POOL_SIZE: "50"
      MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
      MONGO_CONNECTION_TIMEOUT_MS: "2000"
      MONGO_SOCKET_TIMEOUT_MS: "10000"
      MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
      MONGO_WAITING_QUEUE_MS: "2000"
      MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
      ECOMMERCE_DATABASE_NAME: "ecommerce"
      TRANSACTION_EXPIRED_EVENTS_QUEUE_NAME: "pagopa-u-weu-ecommerce-transactions-expiration-queue"
      PENDING_TRANSACTIONS_SCHEDULE_CRON: "0 0 */1 * * *"
      PENDING_TRANSACTIONS_WINDOWS_BATCH_EXECUTION_RATE_MULTIPLIER: "2"
      PENDING_TRANSACTIONS_PARALLEL_EVENTS_TO_PROCESS: "1"
      PENDING_TRANSACTIONS_MAX_TRANSACTIONS_PER_PAGE: "5"
      PENDING_TRANSACTIONS_PAGE_ANALYSIS_DELAY_SECONDS: "1"
      PENDING_TRANSACTIONS_SEND_PAYMENT_RESULT_TIMEOUT_SECONDS: "3900"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-transactions-scheduler-service-blue,service.deployment.environment=uat"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
      OTEL_LOGS_EXPORTER: none
      OTEL_TRACES_SAMPLER: "always_on"
      ECS_SERVICE_NAME: pagopa-ecommerce-transactions-scheduler-service-blue
      ECS_SERVICE_ENVIRONMENT: "uat"
      DEAD_LETTER_LISTENER_TRANSACTION_FIXED_DELAY_MILLIS: "1000"
      DEAD_LETTER_LISTENER_TRANSACTION_MAX_MESSAGE_PER_POLL: "1"
      DEAD_LETTER_LISTENER_TRANSACTION_QUEUE_NAME: "pagopa-u-weu-ecommerce-transactions-dead-letter-queue"
      DEAD_LETTER_LISTENER_NOTIFICATION_FIXED_DELAY_MILLIS: "1000"
      DEAD_LETTER_LISTENER_NOTIFICATION_MAX_MESSAGE_PER_POLL: "1"
      DEAD_LETTER_LISTENER_NOTIFICATION_QUEUE_NAME: "pagopa-u-weu-ecommerce-notifications-service-errors-queue"
      ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_ACCOUNT_NAME: pagopauweuecommercedlsa
      ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_ENDPOINT: https://pagopauweuecommercedlsa.queue.core.windows.net/pagopauweuecommercedlsa
    envSecret:
      MONGO_PASSWORD: mongo-ecommerce-password
      QUEUE_TRANSIENT_CONNECTION_STRING: ecommerce-storage-transient-connection-string
      OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
      ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_KEY: ecommerce-storage-dead-letter-account-key
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaecommercetransactionsschedulerservice
    tag: "1.3.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.ecommerce.internal.uat.platform.pagopa.it"
    path: /pagopa-ecommerce-transactions-scheduler-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enabled: false
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: bbe47ad4-08b3-4925-94c5-1278e5819b86
          resourceGroupName: pagopa-u-ecommerce-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-u-ecommerce-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"
  envConfig:
    MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    ECOMMERCE_DATABASE_NAME: "ecommerce"
    TRANSACTION_EXPIRED_EVENTS_QUEUE_NAME: "pagopa-u-weu-ecommerce-transactions-expiration-queue"
    PENDING_TRANSACTIONS_SCHEDULE_CRON: "0 0 */1 * * *"
    PENDING_TRANSACTIONS_WINDOWS_BATCH_EXECUTION_RATE_MULTIPLIER: "2"
    PENDING_TRANSACTIONS_PARALLEL_EVENTS_TO_PROCESS: "1"
    PENDING_TRANSACTIONS_MAX_TRANSACTIONS_PER_PAGE: "5"
    PENDING_TRANSACTIONS_PAGE_ANALYSIS_DELAY_SECONDS: "1"
    PENDING_TRANSACTIONS_SEND_PAYMENT_RESULT_TIMEOUT_SECONDS: "3900"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-transactions-scheduler-service,service.deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECS_SERVICE_NAME: pagopa-ecommerce-transactions-scheduler-service
    ECS_SERVICE_ENVIRONMENT: "uat"
    DEAD_LETTER_LISTENER_TRANSACTION_FIXED_DELAY_MILLIS: "1000"
    DEAD_LETTER_LISTENER_TRANSACTION_MAX_MESSAGE_PER_POLL: "1"
    DEAD_LETTER_LISTENER_TRANSACTION_QUEUE_NAME: "pagopa-u-weu-ecommerce-transactions-dead-letter-queue"
    DEAD_LETTER_LISTENER_NOTIFICATION_FIXED_DELAY_MILLIS: "1000"
    DEAD_LETTER_LISTENER_NOTIFICATION_MAX_MESSAGE_PER_POLL: "1"
    DEAD_LETTER_LISTENER_NOTIFICATION_QUEUE_NAME: "pagopa-u-weu-ecommerce-notifications-service-errors-queue"
    ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_ACCOUNT_NAME: pagopauweuecommercedlsa
    ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_ENDPOINT: https://pagopauweuecommercedlsa.queue.core.windows.net/pagopauweuecommercedlsa
    NPG_URI: https://stg-ta.nexigroup.com/api/phoenix-0.0
    NPG_READ_TIMEOUT: "10000"
    NPG_CONNECTION_TIMEOUT: "10000"
    NPG_CARDS_PSP_LIST: "BCITITMM,CIPBITMM,BIC36019,UNCRITMM,BPPIITRRXXX,PPAYITR1XXX,BNLIITRR,PASCITMM,WOLLNLB1,IFSPIT21,BPMOIT22,SARDIT31"
    NPG_PAYPAL_PSP_LIST: "BCITITMM,SIGPITM1XXX"
    NPG_MYBANK_PSP_LIST: "BCITITMM,UNCRITMM"
    NPG_BANCOMATPAY_PSP_LIST: "BCITITMM"
    NPG_SATISPAY_PSP_LIST: "SATYLUL1"
    NPG_APPLEPAY_PSP_LIST: "SIGPITM1XXX"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    QUEUE_TRANSIENT_CONNECTION_STRING: ecommerce-storage-transient-connection-string
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    ECOMMERCE_STORAGE_DEAD_LETTER_QUEUE_KEY: ecommerce-storage-dead-letter-account-key
    NPG_API_KEY: npg-api-key
    NPG_CARDS_PSP_KEYS: npg-cards-psp-keys
    NPG_PAYPAL_PSP_KEYS: npg-paypal-psp-keys
    NPG_BANCOMATPAY_PSP_KEYS: npg-bancomatpay-psp-keys
    NPG_MYBANK_PSP_KEYS: npg-mybank-psp-keys
    NPG_SATISPAY_PSP_KEYS: npg-satispay-psp-keys
    NPG_APPLEPAY_PSP_KEYS: npg-apple-pay-psp-keys
  keyvault:
    name: "pagopa-u-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
