microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaecommercetransactionsschedulerservice
    tag: "0.0.1" #improve
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.ecommerce.internal.uat.platform.pagopa.it"
    path: /pagopa-ecommerce-transactions-scheduler-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enabled: false
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: bbe47ad4-08b3-4925-94c5-1278e5819b86
          resourceGroupName: pagopa-u-ecommerce-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-u-ecommerce-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"
  envConfig:
    MONGO_HOST: pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-u-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    ECOMMERCE_DATABASE_NAME: "ecommerce"
    TRANSACTION_EXPIRED_EVENTS_QUEUE_NAME: "pagopa-u-weu-ecommerce-expired-events-queue"
    PENDING_TRANSACTIONS_SCHEDULE_CRON: "0 0 */1 * * *"
    PENDING_TRANSACTIONS_WINDOWS_BATCH_EXECUTION_RATE_MULTIPLIER: "2"
    PENDING_TRANSACTIONS_PARALLEL_EVENTS_TO_PROCESS: "1"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    QUEUE_CONNECTION_STRING: ecommerce-storage-connection-string
  keyvault:
    name: "pagopa-u-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: ""
